### ISSUE TITLE
How can i get EventEmiter output from component?

### ISSUE THREAD

**Issue by GuilhermeDemoliner** [codethatstack/platform#1]
A have EventEmiter output in my component, how i can get the data emited from this.
`@output() foo = new EventEmitter<any>()`

**Comment by codethatstack** [comment]
If I understand your question, you would like to attach an event named 'foo' on the component that was created on the component portal?

To achieve this use, use the activated event from componentPortal.

`
<ng-container [ctsComponentPortal]="componentId" (activated)="onActivated($event)"></ng-container>
`

Then in the handler you now have access to the component itself.

`  onActivated(args: ComponentRef<any>): void {
    console.log('Component Activated', args);
    args.instance.foo.subscribe(x => { ... });
  }`

I hope this answers your question..

**Comment by GuilhermeDemoliner** [comment]
Perfect, thank you.
