### ISSUE TITLE
In production i got the error 'NullInjectorError: No provider for e!'

### ISSUE THREAD

**Issue by GuilhermeDemoliner** [codethatstack/platform#2]
When i run "ng build --prod" and execute the project i got error anywhere that using portals, have idea of what happening?

my angular.json: 

> "optimization": true,
>               "outputHashing": "all",
>               "sourceMap": true,
>               "extractCss": true,
> 			  "namedChunks": true,
>               "aot": true,
>               "extractLicenses": true,
>               "vendorChunk": true,
>               "buildOptimizer": true,
>               "vendorSourceMap": true,

The error:
`ERROR NullInjectorError: StaticInjectorError(r)[class{constructor(e,t){this.portalService=e,this.viewContainerRef=t,this._componentId$=new a.a,this.activated=new i.m,this.deactivated=new i.m,this._subscription=this._componentId$.pipe(Object(u.a)(()=>this.destroyComponent()),Object(l.a)(e=>this.portalService.createComponent({componentId:e,viewContainerRef:t,outletId:this.attachTo,context:this.context,content:this.content}))).subscribe(e=>{this._componentRef=e,this.activated.emit(this._componentRef),this._componentRef.changeDetectorRef.markForCheck()})}ngOnChanges(e){null!=e.componentId&&this._componentId$.next(e.componentId.currentValue)}ngOnDestroy(){this._subscription.unsubscribe(),this.destroyComponent()}destroyComponent(){this._componentRef&&(this.deactivated.emit(this._componentRef),this.viewContainerRef.clear(),this._componentRef.destroy(),this._componentRef=null)}} -> e]: 
  StaticInjectorError(Platform: core)[class{constructor(e,t){this.portalService=e,this.viewContainerRef=t,this._componentId$=new a.a,this.activated=new i.m,this.deactivated=new i.m,this._subscription=this._componentId$.pipe(Object(u.a)(()=>this.destroyComponent()),Object(l.a)(e=>this.portalService.createComponent({componentId:e,viewContainerRef:t,outletId:this.attachTo,context:this.context,content:this.content}))).subscribe(e=>{this._componentRef=e,this.activated.emit(this._componentRef),this._componentRef.changeDetectorRef.markForCheck()})}ngOnChanges(e){null!=e.componentId&&this._componentId$.next(e.componentId.currentValue)}ngOnDestroy(){this._subscription.unsubscribe(),this.destroyComponent()}destroyComponent(){this._componentRef&&(this.deactivated.emit(this._componentRef),this.viewContainerRef.clear(),this._componentRef.destroy(),this._componentRef=null)}} -> e]: 
    NullInjectorError: No provider for e!
    at L.get (http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:202092)
    at http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:207858
    at e (http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:208232)
    at te.get (http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:208381)
    at http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:207858
    at e (http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:208232)
    at te.get (http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:208381)
    at hr (http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:262052)
    at Fr.get (http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:270774)
    at hr (http://192.168.104.32:4200/vendor-es2015.d8c9c68fc37d0f1e26f4.js:1:262052)
on @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
handleError @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
(anonymous) @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
invoke @ polyfills-es2015.6168455069654250df42.js:1
run @ polyfills-es2015.6168455069654250df42.js:1
runOutsideAngular @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
tick @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
(anonymous) @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
invoke @ polyfills-es2015.6168455069654250df42.js:1
onInvoke @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
invoke @ polyfills-es2015.6168455069654250df42.js:1
run @ polyfills-es2015.6168455069654250df42.js:1
run @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
next @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
i @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
__tryOrUnsub @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
next @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
_next @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
next @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
next @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
emit @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
Yo @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
onHasTask @ vendor-es2015.d8c9c68fc37d0f1e26f4.js:1
hasTask @ polyfills-es2015.6168455069654250df42.js:1
_updateTaskCount @ polyfills-es2015.6168455069654250df42.js:1
_updateTaskCount @ polyfills-es2015.6168455069654250df42.js:1
runTask @ polyfills-es2015.6168455069654250df42.js:1
g @ polyfills-es2015.6168455069654250df42.js:1
invokeTask @ polyfills-es2015.6168455069654250df42.js:1
u @ polyfills-es2015.6168455069654250df42.js:1
h @ polyfills-es2015.6168455069654250df42.js:1 `

**Comment by codethatstack** [comment]
What version of Angular are you using?

**Comment by GuilhermeDemoliner** [comment]
My angular version is 8.1.2

**Comment by codethatstack** [comment]
Not sure why this is happening.

Here is a sample version 8 app showing it working: https://github.com/codethatstack/portals_v8

Was able to do a production build and serve the application.

**Comment by codethatstack** [comment]
I've finally tracked down the and fixed this issue with the magic string loading of modules. Will publish a new release soon, just updating demo application.

**Comment by codethatstack** [comment]
@GuilhermeDemoliner Fix has been deployed to npm see #3
